### ISSUE TITLE
Can I use this with gridsome?

### ISSUE THREAD

**Issue by MarkMichos** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#10]
Hi,

since I am not using Nuxt but Gridsome instead, is it possible to rewrite this? I basically got locomotive working but I cannot find a way to have it work when the route changes. It only works on initial pageload or hard reload.

This is my code
https://stackoverflow.com/questions/68149952/update-locomotive-scroll-component-on-route-change-with-vue-js-gridsome

**Comment by DidoMarchet** [comment]
Hi!
I don't use Gridsome but I think you can easily adapt the plugin to the framework.
In my project I use locomotive Scroll in each view and not in the main layout.

Each time the route changes Locomotive Scroll will be recreated.
If you want to use it on the default template, each time the route changes Locomotive Scroll must be updated.

If you want take my plugin as starter!

Have a nice day and kind regards,

Davide
