### ISSUE TITLE
Is possible to combine horizontal scroll and vertical scroll in the same page

### ISSUE THREAD

**Issue by filippodicostanzo** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#11]
Is possible to combine horizontal scroll and vertical scroll in the same page?

**Comment by DidoMarchet** [comment]
Hi!
You can take as example this Codepen [https://codepen.io/cameronknight/pen/qBNvrRQ](https://codepen.io/cameronknight/pen/qBNvrRQ).

Basically you can combine Locomotive and Scrolltrigger and get the horizontal scroll in vertical page.

Have a nice eventing,

Davide

**Comment by filippodicostanzo** [comment]
Yes I know how to create it.

But i have this issue in a nuxt js project

https://stackoverflow.com/questions/66423288/nuxt-with-locomotivescroll-and-gsap

and I wanted to know if it was possible to recreate it with this module

**Comment by anku598** [comment]
@DidoMarchet But how to use element attribute for parallax effect and others effects for horizontal scroll. it's working only when you use it for verticle scroll. 
Thanks
