### ISSUE TITLE
How is it possible to dynamically change the width of the container depending on the content? 

### ISSUE THREAD

**Issue by xdcha** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#12]
Hello. Many thanks for taking the time to explain how to use Locomotive Scroll with Nuxt! I have a small issue with the horizontal scroll. 

I see you use `width:500vw` on the wrapper in order to provide the full scroll distance. You have five divs each set at a width of `100vw`. 

If you remove this width then you don't get any scroll. Also, if I try and use javascript to get the width of my content and add this to the `.example.horizontal` div, this also fails to scroll horizontally. 

Any suggestions? 

Many thanks

**Comment by DidoMarchet** [comment]
Hi!
When you set the sizes call the update method (https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll#gotchas)[https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll#gotchas] or try with a resize.

Let me know,

Davide

**Comment by xdcha** [comment]
Thanks for getting back to me. I may have done this completely the wrong way but something like this? My code does get the container width. 1752px but there's no scroll unless I set the div to something arbitrary like 1000vw for example. 

` mounted() {
    this.$nuxt.$on('update-locomotive', () => {
      this?.locomotive?.update();
    })
    this.$size();
  },
  methods: {
    onScroll(e) {
      if (typeof this.$store._mutations['app/setScroll'] !== 'undefined') {
        this.$store.commit('app/setScroll', {
          isScrolling: this.locomotive.scroll.isScrolling,
          limit: { ...e.limit },
          ...e.scroll, // x, y
        })
      }
    },
    $size(){
      const container = document.querySelector(".o-frame");
      const containerWidth = document.querySelector(".o-frame").offsetWidth;
      setTimeout(function (){
        container.style.width = containerWidth + 'px';
        this.$nuxt.$emit('update-locomotive');
      }, 1000);
    }`
