### ISSUE TITLE
How do i disable scroll when model open in nested Page?

### ISSUE THREAD

**Issue by vicgnana** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#13]
How do i disable scroll when model open in nested Page?  e.g let say i created about page 
template
    LocomotiveScroll ref="scroller" :getted-options="{ smooth: true, getDirection: true,}"
        div class="content__page inner__page"
            aboutPage /
        div
    LocomotiveScroll
template

inside  aboutPage  i have a model which need to disable the scroll when opened how to do that?

**Comment by DidoMarchet** [comment]
Hi!
Thanks for answer!
I need more info to looking into your problem but if I understand properly what you are asking this is the solution:
https://github.com/locomotivemtl/locomotive-scroll/issues/193:

Thanks in advance and kind regards,

Davide

**Comment by vicgnana** [comment]
Hi, 
Thank you very much this is helps but i have one more problem which is the z-index not working for the model should be above the menu but it didnt work in desktop cause of the smooth scroll do you know how to fix this?

**Comment by DidoMarchet** [comment]
Hi!
Unfortunately I don't know  how is set up your project but I think this issue concerns the layout instead of this plugin / guide.

Thanks in advance and kind regards,

Davide
