### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by kieranmansfield** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#15]
For some reason this repo has stopped working for me entirely. No idea what the cause is. 

```
npm ERR! code 1
npm ERR! path /Users/kieranmansfield/Downloads/starter-kit-nuxt-locomotive-scroll-main/node_modules/sharp
npm ERR! command failed
```

**Comment by DidoMarchet** [comment]
Hi @kieranmansfield !
I update the libraries and modules but I don't know what concern your issue. So you can try to remove node modules and package lock, update the repo and reinstall.

Let me know if something change.

Regards,
Davide

**Comment by kieranmansfield** [comment]
@DidoMarchet Works perfectly now, thank you.
