### ISSUE TITLE
 [vuex] do not mutate vuex store state outside mutation handlers.

### ISSUE THREAD

**Issue by MaxVeilleuxMTL** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#2]
First of all thanks for this awesome plugin, working great so far!

I get an error using this exact setup when I resize my screen, please see attached.

**Error: [vuex] do not mutate vuex store state outside mutation handlers.**

<img width="571" alt="nuxt-locoscroll-resize" src="https://user-images.githubusercontent.com/49200337/105080511-e75d2900-5a5e-11eb-81e6-e83ca181eec3.png">

**Comment by DidoMarchet** [comment]
Hi,
thanks and I'm glad this starter-kit is helpful.

The issue was related to the assignment of nested object in the `setScroll` mutation.
Then I solved it spreading the limit object: 
```
this.$store.commit('app/setScroll', {
     isScrolling: this.locomotive.scroll.isScrolling,
     limit: { ...e.limit },
     ...e.scroll // x, y
})
```

Please check and in case close the issue!

Regards,

Davide

**Comment by MaxVeilleuxMTL** [comment]
@DidoMarchet Fixed it ;) thanks!
