### ISSUE TITLE
Using ScrollTrigger in a component of the layout

### ISSUE THREAD

**Issue by MaxVeilleuxMTL** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#4]
I am trying to setup a ScrollTrigger in a component that is imported into a layout (where `<LocomotiveScroll>` is set) :

```
ScrollTrigger.create({
        trigger: this.$el,
        scroller: this.$refs.scroller.locomotive.el,
        toggleClass: { targets: document.body, className: 'theme-light' },
})
```

but I get an error **Cannot read property 'locomotive' of undefined** since this.$refs.scroller only exists in the parent (layout) and not the child component.

How would I preferably get `this.$refs.scroller.locomotive.el` inside the component (which is actually a data-scroll-section)?

**Comment by DidoMarchet** [comment]
Hi,
actually you can work in the parent where the scroll is initialized.
I've updated the Scroll Trigger example with a child component [https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/blob/main/pages/scroll-trigger.vue](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/blob/main/pages/scroll-trigger.vue).
If you need to get reusable the animation you can use a mixin.

Have a nice day,

Davide

**Comment by MaxVeilleuxMTL** [comment]
So there is no way to work with **this.$refs.scroller.locomotive.el** inside a component, outside of the parent where the scroll is initialized?

**Comment by DidoMarchet** [comment]
Hi,
you can pass the locomotive instance as a props:
`<BoxComponent :scroller="$refs.scroller" />`

Inside the component BoxContent, for example, you can retrieve the instance:
```
<script>
export default {
  name: 'BoxComponent',
  props: {
    scroller: {
      type: Object,
      default: () =>({}),
      required: true
    }
  },
  mounted(){
    console.log(this.scroller.locomotive)
  }
}
```
and doing your own logic.

My uses doesn't need this process then you could try to do yours.

I hope it helps,

Davide

**Comment by MaxVeilleuxMTL** [comment]
Hi Davide,

So I am using this technique to pass the scroller to my components via props, so I can have my ScrollTriggers inside of each component.

That being said, if I switch page then come back (ex: Home --> About --> Home) the second time I land on Home I get an undefined value for `this.scroller.locomotive`.

I console logged `this.scroller.locomotive` inside my `SectionManifest.js` component, so you can see it returns `undefined` the second time. Do I need to manually dispose of the scroller?

Please see below :

<img width="554" alt="page-changed-error" src="https://user-images.githubusercontent.com/49200337/106526780-2dc97380-64b4-11eb-90fe-62efbf872e1a.png">

<img width="363" alt="locomotive-undefined" src="https://user-images.githubusercontent.com/49200337/106526797-3457eb00-64b4-11eb-991a-9a0c0353af34.png">

**Comment by DidoMarchet** [comment]
Hi,
Have you tried with a watcher ? The Locomotive Scroll emits an Init event and maybe the prop passed to SectionManifest could be filled after the this event. 

But unfortunately this doesn't concern issues about the starter kit.
My advice is work in the parent preserving the integrity and independency of the component.

Have a nice day and regards,

Davide
