### ISSUE TITLE
Transfering to Starter Kit if already on Locomotive Scroll

### ISSUE THREAD

**Issue by tanjawebdev** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#5]
Hello! Thank you so much for this Plugin, I really hope this is gonna be fixing all my problems. 

I have a Nuxt page with Locomotive Scroll running, but I am always bothered with flickering parts everywhere on scroll. 

I just use the locomotive-scroll.min.js loaded in head. 

Additionally I have this code (and some more) to the global page _.vue:

`
    // Locomotive Scroll

    var scroll = new LocomotiveScroll({
      el: document.querySelector("[data-scroll-container]"),
      smooth: true,
      smoothMobile: false,
      offset: ["0", "0"],
      lerp: 0.05,
      touchMultiplier: 0,
    });

    scroll.scrollTo(0);

    if ($(".c-scrollbar").length > 1) {
      $(".c-scrollbar:first-of-type").remove();
    }

    var initDomHeight = $("#footer").offset().top;

    var windowWidth = $(window).width();
    var leftDist = 0;
    var topDist = 0;

    if ($("#startVideo").length) {
      var startOffsetVideoTop = $("#startVideo").offset().top;
      var gridWidth = $(".videowrap").outerWidth();

      $("#startTitle .h2").mouseover(function () {
        scroll.scrollTo(180);
      });
    }

    scroll.on("scroll", (func) => {
      // Change width of Video on scroll
      if ($("#startVideo").length) {
        var curOffsetVideoTop = $("#startVideo").offset().top;
        var percentPosition = (100 / startOffsetVideoTop) * curOffsetVideoTop;

        if (curOffsetVideoTop > 0) {
          var videoWidth =
            gridWidth +
            (windowWidth - gridWidth) *
              ((startOffsetVideoTop - curOffsetVideoTop) / startOffsetVideoTop);
        } else {
          var videoWidth = windowWidth;
          $("#startVideo video").attr("loop", "loop");
          if ($("#startVideo video")[0].paused) {
            $("#startVideo video")[0].play();
          }
        }

        $(".videowrap").css("width", videoWidth);
      }`

Do I have to change the whole code and remove everything from Locomotive scroll to be able to run the starter Kit, or can I install your package as well as having the lovomotice scroll definitions? 

`  var scroll = new LocomotiveScroll({
      el: document.querySelector("[data-scroll-container]"),
      smooth: true,
      smoothMobile: false,
      offset: ["0", "0"],
      lerp: 0.05,
      touchMultiplier: 0,
    });`

**Comment by tanjawebdev** [comment]
This is my current project: 
https://gowest.go-stage.at/de/

user: customer
passwort: gowest

**Comment by DidoMarchet** [comment]
Hi!
I think you can easily include both the plugin and the component.

First of all install the [dependencies](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/blob/main/package.json) and copy [Locomotive Scroll folder](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll).

After that use the [plugin](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/tree/main/plugins) and [configure nuxt](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/blob/main/configuration/plugins.js).

(Wrap your content)[https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/blob/main/pages/on-call.vue] with the component and pass the options.

Replace `scroll.scrollTo(0);`, `scroll.on("scroll", (func) => {....}` with `this.$refs.scroller.locomotive.scrollTo(0);` or `this.$refs.scroller.locomotive.on("scroll", (func) => {....}`.

I hope it could be useful and let me know,

Davide

**Comment by tanjawebdev** [comment]
Thank you very much, it works perfect so far!
