### ISSUE TITLE
Loading components - Not working?

### ISSUE THREAD

**Issue by kieranmansfield** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#6]
I've tried to add a loading component to the repository, for some reason none of the loading options (bar, custom component, indicator etc) work? I can't figure what I need to change or configure to actual get this working? The Nuxt documentation says it should work out of the box.

**Comment by DidoMarchet** [comment]
Hi,
I've splitting the configuration in modules:
[https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/tree/main/configuration](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll/tree/main/configuration)
and all modules are called in the Nuxt config.

Have you work with these files?

Fell you free to copy, if necessary, the Locomotive plugin and component in your own boilerplate!

Let me know and regards,

Davide

**Comment by DidoMarchet** [comment]
Hi,
I tried out of curiosity using `this.$nuxt.$loading` into the `mounted` hook as [documentation](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-loading) says and it works as expected.

```
export default {
  mounted(){
    this.$nextTick(() => {
      this.$nuxt.$loading.start()
      setTimeout(() => this.$nuxt.$loading.finish(), 500)
    })
  }
}
```

Then I think this issues could be closed!

Have a nice day and regards,

Davide

**Comment by kieranmansfield** [comment]
Awesome, this has sorted it. I think I was looking at the wrong part of the config for this type of config.
