### ISSUE TITLE
Nuxt-Links and Scrolling Behaviour Issues

### ISSUE THREAD

**Issue by kieranmansfield** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#7]
hey, 
I'm having some issues when using the <nuxt-link> for internal links. I've put some links at the bottom of the page, when I click a link using the same layout as the page i'm navigating to - for some reason the default behavior is that the page i've navigated to starts at the bottom of the page. In the exact same place or half way down the page. 

I've already tried a solution to the problem and for some reason none of them are working. I've tried adding in [scrollToTop](https://nuxtjs.org/docs/2.x/components-glossary/pages-scrolltotop) and overwriting [scrollBehaviour](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#scrollbehavior) and i've tried adding in [this](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll#gotchas) and i've also tried to locomotive scroll to scroll to top on mounting 
- this.$refs.scroller.locomotive.scrollTo(0) 

I'm really not sure how to solve this, so i'd thought i'd ask. For some reason if I use anchor tags, I have no problems at all.

**Comment by DidoMarchet** [comment]
Hi!
Do you use the starter kit I've published? 
If you check the demo when you browse a new page it returns on the top as expected.
Btw can you share your implementation ?

Thanks and have a nice evening,

Davide

**Comment by kieranmansfield** [comment]
Yeah, I'm using the starter kit. The Demo works as expected. I'm not really sure what would be best to share? 

UPDATE - I've fixed it now. Essentially I moved the plugin declaration & rest of the wrapper into the layouts folder to simplify the pages a bit - that was the cause of the problem. All sorting fine now.

**Comment by DidoMarchet** [comment]
Hi!

First of all try to add  correctly (or remove all) the `data-scroll-section` attribute on each child of `main` tag.

```
<header data-scroll-section />
<div data-scroll-section />
<footer data-scroll-section />
```

and not 
```
<header data-scroll-section />
<div>
	<div data-scroll-section />
	<div data-scroll-section />
	...
</div>
<footer data-scroll-section />
```

Let me know and in case share me the code.

Have a nice day,

Davide

**Comment by DidoMarchet** [comment]
> UPDATE - I've fixed it now. Essentially I moved the plugin declaration & rest of the wrapper into the layouts folder to simplify the pages a bit - that was the cause of the problem. All sorting fine now. 

Hi, nice to hear this! If you have any question I'm here and if you find helpful this repo please give a star if you didn't yet!
Have a nice day,
Davide
