### ISSUE TITLE
Package.json - library & utils dependencies

### ISSUE THREAD

**Issue by kieranmansfield** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#8]
Just cloned the repo and ran npm run generate and terminal is throwing errors. I tried to update the dependencies and got this error -  

`npm ERR! code ENOLOCAL
npm ERR! Could not install from "../library" as it does not contain a package.json file.`

I also ran npm outdated and it says the library package & utils packages are missing.

```
Package                         Current          Wanted  Latest  Location
library                         MISSING          linked  linked  app
utils                           MISSING          linked  linked  app
```

Not sure what's going on with the package.json, or how to get around this. Any Ideas?

**Comment by DidoMarchet** [comment]
Hi @kieranmansfield ,
thanks to notify the issue.

I forgot to clean the boilerplate but now I you should be able to install the packages.

Use `npm i --legacy-peer-deps`  for peer dependencies.

Let me know!

Thanks in advance and kind regards,

Davide

**Comment by kieranmansfield** [comment]
All sorted. Thanks!!

The only thing is there's a lot of security vulnerabilities and they need to be manually reviewed. :/

`found 253 vulnerabilities (1 low, 238 moderate, 14 high)`

**Comment by DidoMarchet** [comment]
Hi,
in this starter kit I included more than we need.
You can get rid of all the clutter!

Have a nice day and kind regards,

Davide
