### ISSUE TITLE
Need a delay on the scrollto fired when using a url hash

### ISSUE THREAD

**Issue by MaxVeilleuxMTL** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#9]
I am using a hash in my url in order to trigger a scrollto to a section, but the scrollto is fired too soon.

LocomotiveScroll in my Nuxt project is initiated before my content is fully generated, so the scrollto is fired too early and scrolls to random places.

I added a delay to the file `dist/locomotive-scroll.esm.js` which makes it work like this :

```
if (window.location.hash) {
        // Get the hash without the '#' and find the matching element
        var id = window.location.hash.slice(1, window.location.hash.length);
        var target = document.getElementById(id); // If found, scroll to the element

        if (target) {
          setTimeout(() => {
            this.scroll.scrollTo(target);
          }, 1500);
        } 
}
```

but this won't persist through version updates and new `npm install`'s obviously.

Is there some way we could add a delay when necessary, or trigger the scrollto function with an event (and cancel the original one) when we have a hash in the url?

Thanks a lot !

**Comment by DidoMarchet** [comment]
Hi!
you can try to add an event inside the child component (something like `this.$nuxt.$emit('load')` if you use the $nuxt helper or this.$emit('load')) and when it's triggered do the scroll action
`
   this.$nuxt.$on('load', () => {
       MY LOGIC TO SCROLL
  })
`

You can try inspiration from [https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll#gotchas](https://github.com/DidoMarchet/starter-kit-nuxt-locomotive-scroll#gotchas).

Let me know if it works and if not we can try something else.

Have a nice day,

Davide

**Comment by MaxVeilleuxMTL** [comment]
Hello!

Thanks for your answer :)

Unfortunately this won't change the default behaviour that the library has in the file `dist/locomotive-scroll.esm.js ` that triggers the `scrollTo()` method when there is a hash in the url, and as soon as the scroll is ready.

Adding a `load` method and use that to trigger a custom `scrollTo()` won't prevent the default hash scroll there is in the lib, so we'll probably see the thing scroll once to a random place, then a second time to the good place, which is not really what I would want :P 

Would it be possible to add an option to the scroll instance, for example `scrollToHashDelay: 1500` that will always take 1.5 seconds to trigger a `scrollTo` when we have a hash in the url?

Or maybe another option like `scrollToHash: false` so that we can trigger that scroll manually without the default scroll to happen beforehand?

**Comment by DidoMarchet** [comment]
Hi,
Unfortunately I'm quite busy at the moment then I'm not able to add this feature or find a solution in a short time. 
If you want to try and make a pr or maybe next week I try to check.

Thanks and regards,
Davide
